// ============================================================
// ORBIPULSE DEMO SEED DATASET
// Source: SW-SEED-001 RevA0
// For dev/test/demo only — not production customer truth
// ============================================================

import type {
  Tenant, User, Site, Zone, Device, LatestState, Command, CommandAck,
  DeviceEvent, Fault, Schedule, WeatherCache, TelemetryHistory, ServiceRecord, AccessGrant
} from '@/types';

// ─── TENANTS ─────────────────────────────────────────────────

export const MOCK_TENANTS: Tenant[] = [
  {
    tenant_id: 'TENANT_DEMO_AGRI',
    tenant_name: 'Suresh Farms',
    tenant_type: 'agriculture',
    contact_email: 'suresh@sureshfarms.in',
    contact_phone: '+91-9876543210',
    address: 'Village Kadup, Udupi, Karnataka - 576101',
    subscription_plan: 'pro_agriculture',
    account_status: 'active',
    created_at: '2026-01-15T08:00:00.000Z',
    updated_at: '2026-06-10T10:00:00.000Z',
  },
  {
    tenant_id: 'TENANT_DEMO_MUNI',
    tenant_name: 'Udupi Municipal Council',
    tenant_type: 'municipal',
    contact_email: 'ops@udupi-mc.gov.in',
    contact_phone: '+91-8201234567',
    address: 'Municipal Office, Car Street, Udupi - 576101',
    subscription_plan: 'municipal_basic',
    account_status: 'active',
    created_at: '2026-02-01T08:00:00.000Z',
    updated_at: '2026-06-10T10:00:00.000Z',
  },
];

// ─── USERS ───────────────────────────────────────────────────

export const MOCK_USERS: User[] = [
  {
    user_id: 'USR_ADMIN_001',
    tenant_id: 'TENANT_DEMO_AGRI',
    user_email: 'admin@orbipulse.com',
    user_name: 'Prashant Raju',
    role: 'founder_admin',
    account_status: 'active',
    mfa_enabled: true,
    last_login_at: '2026-06-16T07:30:00.000Z',
    assigned_site_ids: ['SITE_FARM_001', 'SITE_FARM_002', 'SITE_MUNI_001'],
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-06-16T07:30:00.000Z',
  },
  {
    user_id: 'USR_FARMER_001',
    tenant_id: 'TENANT_DEMO_AGRI',
    user_email: 'farmer@orbipulse.com',
    user_name: 'Suresh Kumar',
    role: 'farmer',
    account_status: 'active',
    mfa_enabled: false,
    last_login_at: '2026-06-15T18:00:00.000Z',
    assigned_site_ids: ['SITE_FARM_001', 'SITE_FARM_002'],
    created_at: '2026-01-15T08:00:00.000Z',
    updated_at: '2026-06-15T18:00:00.000Z',
  },
  {
    user_id: 'USR_INSTALLER_001',
    tenant_id: 'TENANT_DEMO_AGRI',
    user_email: 'installer@orbipulse.com',
    user_name: 'Ramesh Shetty',
    role: 'installer',
    account_status: 'active',
    mfa_enabled: false,
    last_login_at: '2026-06-14T10:00:00.000Z',
    assigned_site_ids: ['SITE_FARM_001'],
    created_at: '2026-01-20T08:00:00.000Z',
    updated_at: '2026-06-14T10:00:00.000Z',
  },
  {
    user_id: 'USR_SERVICE_001',
    tenant_id: 'TENANT_DEMO_AGRI',
    user_email: 'service@orbipulse.com',
    user_name: 'Anand Pai',
    role: 'service_technician',
    account_status: 'active',
    mfa_enabled: false,
    last_login_at: '2026-06-13T14:00:00.000Z',
    assigned_site_ids: ['SITE_FARM_001', 'SITE_FARM_002'],
    created_at: '2026-02-01T08:00:00.000Z',
    updated_at: '2026-06-13T14:00:00.000Z',
  },
  {
    user_id: 'USR_MUNI_001',
    tenant_id: 'TENANT_DEMO_MUNI',
    user_email: 'operator@orbipulse.com',
    user_name: 'Nagesh Rao',
    role: 'municipal_operator',
    account_status: 'active',
    mfa_enabled: false,
    last_login_at: '2026-06-16T06:00:00.000Z',
    assigned_site_ids: ['SITE_MUNI_001'],
    created_at: '2026-02-05T08:00:00.000Z',
    updated_at: '2026-06-16T06:00:00.000Z',
  },
];

// ─── MOCK PASSWORDS (demo only) ──────────────────────────────

export const MOCK_CREDENTIALS: Record<string, string> = {
  'admin@orbipulse.com': 'Admin@123',
  'farmer@orbipulse.com': 'Farmer@123',
  'installer@orbipulse.com': 'Install@123',
  'service@orbipulse.com': 'Service@123',
  'operator@orbipulse.com': 'Operator@123',
};

// ─── ACCESS GRANTS ───────────────────────────────────────────
// Mirrors each MOCK_USERS entry's existing role/tenant_id/assigned_site_ids
// exactly, as long-valid grants (no expiry behavior change from today).
// These represent accounts already provisioned by E-Actuell / tenant
// authority — not self-registered. device_id is left unset (not
// restricted below site level) since no current account has device-level
// restriction; zone_id is left unset since no Site/Device record in this
// dataset carries a zone_id yet.

const FAR_FUTURE = '2099-12-31T23:59:59.000Z';

export const MOCK_ACCESS_GRANTS: AccessGrant[] = [
  // USR_ADMIN_001 — founder_admin — spans both demo tenants (admin's
  // assigned_site_ids today includes a municipal site outside their own
  // tenant_id, so two grants are needed to cover the same scope).
  { grant_id: 'GRANT-001', user_id: 'USR_ADMIN_001', tenant_id: 'TENANT_DEMO_AGRI', site_id: 'SITE_FARM_001', role: 'founder_admin', valid_from: '2026-01-01T00:00:00.000Z', valid_until: FAR_FUTURE },
  { grant_id: 'GRANT-002', user_id: 'USR_ADMIN_001', tenant_id: 'TENANT_DEMO_AGRI', site_id: 'SITE_FARM_002', role: 'founder_admin', valid_from: '2026-01-01T00:00:00.000Z', valid_until: FAR_FUTURE },
  { grant_id: 'GRANT-003', user_id: 'USR_ADMIN_001', tenant_id: 'TENANT_DEMO_MUNI', site_id: 'SITE_MUNI_001', role: 'founder_admin', valid_from: '2026-01-01T00:00:00.000Z', valid_until: FAR_FUTURE },

  // USR_FARMER_001 — farmer — TENANT_DEMO_AGRI, two sites
  { grant_id: 'GRANT-004', user_id: 'USR_FARMER_001', tenant_id: 'TENANT_DEMO_AGRI', site_id: 'SITE_FARM_001', role: 'farmer', valid_from: '2026-01-15T08:00:00.000Z', valid_until: FAR_FUTURE },
  { grant_id: 'GRANT-005', user_id: 'USR_FARMER_001', tenant_id: 'TENANT_DEMO_AGRI', site_id: 'SITE_FARM_002', role: 'farmer', valid_from: '2026-01-15T08:00:00.000Z', valid_until: FAR_FUTURE },

  // USR_INSTALLER_001 — installer — TENANT_DEMO_AGRI, single site
  { grant_id: 'GRANT-006', user_id: 'USR_INSTALLER_001', tenant_id: 'TENANT_DEMO_AGRI', site_id: 'SITE_FARM_001', role: 'installer', valid_from: '2026-01-20T08:00:00.000Z', valid_until: FAR_FUTURE },

  // USR_SERVICE_001 — service_technician — TENANT_DEMO_AGRI, two sites
  { grant_id: 'GRANT-007', user_id: 'USR_SERVICE_001', tenant_id: 'TENANT_DEMO_AGRI', site_id: 'SITE_FARM_001', role: 'service_technician', valid_from: '2026-02-01T08:00:00.000Z', valid_until: FAR_FUTURE },
  { grant_id: 'GRANT-008', user_id: 'USR_SERVICE_001', tenant_id: 'TENANT_DEMO_AGRI', site_id: 'SITE_FARM_002', role: 'service_technician', valid_from: '2026-02-01T08:00:00.000Z', valid_until: FAR_FUTURE },

  // USR_MUNI_001 — municipal_operator — TENANT_DEMO_MUNI, single site
  { grant_id: 'GRANT-009', user_id: 'USR_MUNI_001', tenant_id: 'TENANT_DEMO_MUNI', site_id: 'SITE_MUNI_001', role: 'municipal_operator', valid_from: '2026-02-05T08:00:00.000Z', valid_until: FAR_FUTURE },
];

// ─── SITES ───────────────────────────────────────────────────

export const MOCK_SITES: Site[] = [
  {
    site_id: 'SITE_FARM_001',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_name: 'North Field - Borewell 1',
    site_type: 'farm',
    location_address: 'Survey No. 112, Kadup Village, Udupi',
    lat: 13.3409,
    lon: 74.7421,
    timezone: 'Asia/Kolkata',
    created_at: '2026-01-15T08:00:00.000Z',
    updated_at: '2026-06-10T10:00:00.000Z',
  },
  {
    site_id: 'SITE_FARM_002',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_name: 'South Field - Borewell 2',
    site_type: 'farm',
    location_address: 'Survey No. 205, Kadup Village, Udupi',
    lat: 13.3398,
    lon: 74.7445,
    timezone: 'Asia/Kolkata',
    created_at: '2026-01-20T08:00:00.000Z',
    updated_at: '2026-06-10T10:00:00.000Z',
  },
  {
    site_id: 'SITE_MUNI_001',
    tenant_id: 'TENANT_DEMO_MUNI',
    site_name: 'Ward 4 - Main Distribution Line',
    site_type: 'municipal',
    location_address: 'Main Road Junction, Ward 4, Udupi',
    lat: 13.3316,
    lon: 74.7459,
    timezone: 'Asia/Kolkata',
    created_at: '2026-02-01T08:00:00.000Z',
    updated_at: '2026-06-10T10:00:00.000Z',
  },
];

// ─── ZONES ───────────────────────────────────────────────────
// Frozen hierarchy: Tenant -> Site -> Zone -> Device. Every device below
// carries exactly one zone_id, matching one of these zones.

export const MOCK_ZONES: Zone[] = [
  {
    zone_id: 'ZONE_FARM001_A',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_001',
    zone_name: 'Borewell Zone',
    zone_type: 'borewell',
    lat: 13.3409,
    lon: 74.7421,
    created_at: '2026-01-20T08:00:00.000Z',
    updated_at: '2026-06-10T10:00:00.000Z',
  },
  {
    zone_id: 'ZONE_FARM001_B',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_001',
    zone_name: 'Sprinkler Zone A',
    zone_type: 'sprinkler',
    lat: 13.3415,
    lon: 74.7418,
    created_at: '2026-01-22T09:00:00.000Z',
    updated_at: '2026-06-10T10:00:00.000Z',
  },
  {
    zone_id: 'ZONE_FARM002_A',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_002',
    zone_name: 'South Field Zone',
    zone_type: 'mixed',
    lat: 13.3398,
    lon: 74.7445,
    created_at: '2026-02-01T10:00:00.000Z',
    updated_at: '2026-06-10T10:00:00.000Z',
  },
  {
    zone_id: 'ZONE_MUNI001_4A',
    tenant_id: 'TENANT_DEMO_MUNI',
    site_id: 'SITE_MUNI_001',
    zone_name: 'Zone 4A',
    zone_type: 'distribution',
    lat: 13.3316,
    lon: 74.7459,
    created_at: '2026-02-10T08:00:00.000Z',
    updated_at: '2026-06-10T10:00:00.000Z',
  },
  {
    zone_id: 'ZONE_MUNI001_4B',
    tenant_id: 'TENANT_DEMO_MUNI',
    site_id: 'SITE_MUNI_001',
    zone_name: 'Zone 4B',
    zone_type: 'distribution',
    lat: 13.3320,
    lon: 74.7462,
    created_at: '2026-02-10T09:00:00.000Z',
    updated_at: '2026-06-10T10:00:00.000Z',
  },
];

// ─── DEVICES ─────────────────────────────────────────────────

export const MOCK_DEVICES: Device[] = [
  {
    device_id: 'D001',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_001',
    zone_id: 'ZONE_FARM001_A',
    device_name: 'Borewell Valve 1',
    product_variant: 'orbidrive_agriculture',
    hw_revision: 'HW-REV-B1',
    fw_baseline_id: 'FW-AGRI-2.1.4',
    dsn: 'OD-AGR-2026-00001',
    aws_thing_name: 'orbidrive-TENANT_DEMO_AGRI-D001',
    certificate_status: 'active',
    provisioning_state: 'provisioned',
    ownership_state: 'assigned',
    lat: 13.3409,
    lon: 74.7421,
    sensor_fitted_map: { flow_sensor: true, wet_sensor: true, water_quality: false },
    commissioning_date: '2026-01-20',
    created_at: '2026-01-20T08:00:00.000Z',
    updated_at: '2026-06-10T10:00:00.000Z',
  },
  {
    device_id: 'D002',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_001',
    zone_id: 'ZONE_FARM001_A',
    device_name: 'Drip Line Valve 2',
    product_variant: 'orbidrive_agriculture',
    hw_revision: 'HW-REV-B1',
    fw_baseline_id: 'FW-AGRI-2.1.4',
    dsn: 'OD-AGR-2026-00002',
    aws_thing_name: 'orbidrive-TENANT_DEMO_AGRI-D002',
    certificate_status: 'active',
    provisioning_state: 'provisioned',
    ownership_state: 'assigned',
    lat: 13.3412,
    lon: 74.7425,
    sensor_fitted_map: { flow_sensor: true, wet_sensor: false, water_quality: false },
    commissioning_date: '2026-01-20',
    created_at: '2026-01-20T08:30:00.000Z',
    updated_at: '2026-06-10T10:00:00.000Z',
  },
  {
    device_id: 'D003',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_001',
    zone_id: 'ZONE_FARM001_B',
    device_name: 'Sprinkler Zone A',
    product_variant: 'orbidrive_agriculture',
    hw_revision: 'HW-REV-B1',
    fw_baseline_id: 'FW-AGRI-2.1.3',
    dsn: 'OD-AGR-2026-00003',
    aws_thing_name: 'orbidrive-TENANT_DEMO_AGRI-D003',
    certificate_status: 'active',
    provisioning_state: 'provisioned',
    ownership_state: 'assigned',
    lat: 13.3415,
    lon: 74.7418,
    sensor_fitted_map: { flow_sensor: false, wet_sensor: true, water_quality: false },
    commissioning_date: '2026-01-22',
    created_at: '2026-01-22T09:00:00.000Z',
    updated_at: '2026-06-10T10:00:00.000Z',
  },
  {
    device_id: 'D004',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_002',
    zone_id: 'ZONE_FARM002_A',
    device_name: 'Borewell Valve 3',
    product_variant: 'orbidrive_agriculture',
    hw_revision: 'HW-REV-B2',
    fw_baseline_id: 'FW-AGRI-2.1.4',
    dsn: 'OD-AGR-2026-00004',
    aws_thing_name: 'orbidrive-TENANT_DEMO_AGRI-D004',
    certificate_status: 'active',
    provisioning_state: 'provisioned',
    ownership_state: 'assigned',
    lat: 13.3398,
    lon: 74.7445,
    sensor_fitted_map: { flow_sensor: true, wet_sensor: true, water_quality: false },
    commissioning_date: '2026-02-01',
    created_at: '2026-02-01T10:00:00.000Z',
    updated_at: '2026-06-10T10:00:00.000Z',
  },
  {
    device_id: 'D005',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_002',
    zone_id: 'ZONE_FARM002_A',
    device_name: 'Field Valve South',
    product_variant: 'orbidrive_agriculture',
    hw_revision: 'HW-REV-B2',
    fw_baseline_id: 'FW-AGRI-2.1.4',
    dsn: 'OD-AGR-2026-00005',
    aws_thing_name: 'orbidrive-TENANT_DEMO_AGRI-D005',
    certificate_status: 'active',
    provisioning_state: 'provisioned',
    ownership_state: 'assigned',
    lat: 13.3401,
    lon: 74.7450,
    sensor_fitted_map: { flow_sensor: true, wet_sensor: false, water_quality: false },
    commissioning_date: '2026-02-01',
    created_at: '2026-02-01T10:30:00.000Z',
    updated_at: '2026-06-10T10:00:00.000Z',
  },
  {
    device_id: 'D006',
    tenant_id: 'TENANT_DEMO_MUNI',
    site_id: 'SITE_MUNI_001',
    zone_id: 'ZONE_MUNI001_4A',
    device_name: 'Zone 4A Distribution Valve',
    product_variant: 'orbidrive_municipal',
    hw_revision: 'HW-REV-C1',
    fw_baseline_id: 'FW-MUNI-3.0.1',
    dsn: 'OD-MUN-2026-00001',
    aws_thing_name: 'orbidrive-TENANT_DEMO_MUNI-D006',
    certificate_status: 'active',
    provisioning_state: 'provisioned',
    ownership_state: 'assigned',
    lat: 13.3316,
    lon: 74.7459,
    sensor_fitted_map: { flow_sensor: true, wet_sensor: false, water_quality: true },
    commissioning_date: '2026-02-10',
    created_at: '2026-02-10T08:00:00.000Z',
    updated_at: '2026-06-10T10:00:00.000Z',
  },
  {
    device_id: 'D007',
    tenant_id: 'TENANT_DEMO_MUNI',
    site_id: 'SITE_MUNI_001',
    zone_id: 'ZONE_MUNI001_4B',
    device_name: 'Zone 4B Pressure Valve',
    product_variant: 'orbidrive_municipal',
    hw_revision: 'HW-REV-C1',
    fw_baseline_id: 'FW-MUNI-3.0.1',
    dsn: 'OD-MUN-2026-00002',
    aws_thing_name: 'orbidrive-TENANT_DEMO_MUNI-D007',
    certificate_status: 'active',
    provisioning_state: 'provisioned',
    ownership_state: 'assigned',
    lat: 13.3320,
    lon: 74.7462,
    sensor_fitted_map: { flow_sensor: true, wet_sensor: false, water_quality: false },
    commissioning_date: '2026-02-10',
    created_at: '2026-02-10T09:00:00.000Z',
    updated_at: '2026-06-10T10:00:00.000Z',
  },
];

// ─── LATEST STATE ─────────────────────────────────────────────

export const MOCK_LATEST_STATE: LatestState[] = [
  {
    device_id: 'D001',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_001',
    valve_state: 'open',
    valve_position_pct: 100,
    position_confidence: 'valid',
    battery_v: 12.4,
    battery_state: 'good',
    firmware_state: 'healthy',
    manual_active: false,
    wet_active: false,
    signal_strength: 78,
    availability: 'online',
    stale_flag: false,
    motor_current_a: 0.8,
    fault_code: null,
    reason_code: null,
    active_fault_codes: [],
    last_seen_at: new Date(Date.now() - 15000).toISOString(),
    last_telemetry_seq: 1042,
    fw_version: 'FW-AGRI-2.1.4',
    updated_at: new Date(Date.now() - 15000).toISOString(),
  },
  {
    device_id: 'D002',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_001',
    valve_state: 'closed',
    valve_position_pct: 0,
    position_confidence: 'valid',
    battery_v: 11.8,
    battery_state: 'good',
    firmware_state: 'healthy',
    manual_active: false,
    wet_active: false,
    signal_strength: 65,
    availability: 'online',
    stale_flag: false,
    motor_current_a: 0.0,
    fault_code: null,
    reason_code: null,
    active_fault_codes: [],
    last_seen_at: new Date(Date.now() - 8000).toISOString(),
    last_telemetry_seq: 867,
    fw_version: 'FW-AGRI-2.1.4',
    updated_at: new Date(Date.now() - 8000).toISOString(),
  },
  {
    device_id: 'D003',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_001',
    valve_state: 'fault',
    valve_position_pct: 45,
    position_confidence: 'invalid',
    battery_v: 10.2,
    battery_state: 'low',
    firmware_state: 'degraded',
    manual_active: false,
    wet_active: false,
    signal_strength: 42,
    availability: 'online',
    stale_flag: false,
    motor_current_a: 2.1,
    fault_code: 'FLT_MOTOR_OVERCURRENT',
    reason_code: 'RSN_FAULT_ACTIVE',
    active_fault_codes: ['FLT_MOTOR_OVERCURRENT', 'FLT_BATTERY_LOW'],
    last_seen_at: new Date(Date.now() - 22000).toISOString(),
    last_telemetry_seq: 445,
    fw_version: 'FW-AGRI-2.1.3',
    updated_at: new Date(Date.now() - 22000).toISOString(),
  },
  {
    device_id: 'D004',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_002',
    valve_state: 'closed',
    valve_position_pct: 0,
    position_confidence: 'valid',
    battery_v: 12.1,
    battery_state: 'good',
    firmware_state: 'healthy',
    manual_active: true,
    wet_active: false,
    signal_strength: 81,
    availability: 'online',
    stale_flag: false,
    motor_current_a: 0.0,
    fault_code: null,
    reason_code: 'RSN_MANUAL_ACTIVE',
    active_fault_codes: [],
    last_seen_at: new Date(Date.now() - 5000).toISOString(),
    last_telemetry_seq: 321,
    fw_version: 'FW-AGRI-2.1.4',
    updated_at: new Date(Date.now() - 5000).toISOString(),
  },
  {
    device_id: 'D005',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_002',
    valve_state: 'unknown',
    valve_position_pct: 0,
    position_confidence: 'stale',
    battery_v: 9.8,
    battery_state: 'critical',
    firmware_state: 'unknown',
    manual_active: false,
    wet_active: false,
    signal_strength: 0,
    availability: 'offline',
    stale_flag: true,
    stale_age_sec: 3620,
    motor_current_a: 0.0,
    fault_code: 'FLT_LTE_DISCONNECTED',
    reason_code: 'RSN_DEVICE_OFFLINE',
    active_fault_codes: ['FLT_LTE_DISCONNECTED', 'FLT_BATTERY_CRITICAL'],
    last_seen_at: new Date(Date.now() - 3620000).toISOString(),
    last_telemetry_seq: 199,
    fw_version: 'FW-AGRI-2.1.4',
    updated_at: new Date(Date.now() - 3620000).toISOString(),
  },
  {
    device_id: 'D006',
    tenant_id: 'TENANT_DEMO_MUNI',
    site_id: 'SITE_MUNI_001',
    valve_state: 'open',
    valve_position_pct: 60,
    position_confidence: 'valid',
    battery_v: 12.6,
    battery_state: 'good',
    firmware_state: 'healthy',
    manual_active: false,
    wet_active: false,
    signal_strength: 88,
    availability: 'online',
    stale_flag: false,
    motor_current_a: 1.1,
    fault_code: null,
    reason_code: null,
    active_fault_codes: [],
    last_seen_at: new Date(Date.now() - 10000).toISOString(),
    last_telemetry_seq: 2101,
    fw_version: 'FW-MUNI-3.0.1',
    updated_at: new Date(Date.now() - 10000).toISOString(),
  },
  {
    device_id: 'D007',
    tenant_id: 'TENANT_DEMO_MUNI',
    site_id: 'SITE_MUNI_001',
    valve_state: 'closed',
    valve_position_pct: 0,
    position_confidence: 'valid',
    battery_v: 11.5,
    battery_state: 'good',
    firmware_state: 'healthy',
    manual_active: false,
    wet_active: false,
    signal_strength: 72,
    availability: 'online',
    stale_flag: false,
    motor_current_a: 0.0,
    fault_code: null,
    reason_code: null,
    active_fault_codes: [],
    last_seen_at: new Date(Date.now() - 12000).toISOString(),
    last_telemetry_seq: 1888,
    fw_version: 'FW-MUNI-3.0.1',
    updated_at: new Date(Date.now() - 12000).toISOString(),
  },
];

// ─── COMMANDS (history) ──────────────────────────────────────

export const MOCK_COMMANDS: Command[] = [
  {
    command_id: 'CMD-2026-0001',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_001',
    device_id: 'D001',
    command_type: 'open',
    issued_by: 'USR_FARMER_001',
    issued_at: new Date(Date.now() - 3600000).toISOString(),
    expires_at: new Date(Date.now() - 3540000).toISOString(),
    current_ack_stage: 'completed',
    result: 'success',
    final_position_pct: 100,
    execution_duration_ms: 8200,
    completed_at: new Date(Date.now() - 3592000).toISOString(),
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date(Date.now() - 3592000).toISOString(),
  },
  {
    command_id: 'CMD-2026-0002',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_001',
    device_id: 'D002',
    command_type: 'close',
    issued_by: 'USR_FARMER_001',
    issued_at: new Date(Date.now() - 1800000).toISOString(),
    expires_at: new Date(Date.now() - 1740000).toISOString(),
    current_ack_stage: 'completed',
    result: 'success',
    final_position_pct: 0,
    execution_duration_ms: 7100,
    completed_at: new Date(Date.now() - 1792000).toISOString(),
    created_at: new Date(Date.now() - 1800000).toISOString(),
    updated_at: new Date(Date.now() - 1792000).toISOString(),
  },
  {
    command_id: 'CMD-2026-0003',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_001',
    device_id: 'D003',
    command_type: 'open',
    issued_by: 'USR_FARMER_001',
    issued_at: new Date(Date.now() - 900000).toISOString(),
    expires_at: new Date(Date.now() - 840000).toISOString(),
    current_ack_stage: 'failed',
    result: 'failure',
    reason_code: 'RSN_FAULT_ACTIVE',
    fault_code: 'FLT_MOTOR_OVERCURRENT',
    execution_duration_ms: 3200,
    completed_at: new Date(Date.now() - 896000).toISOString(),
    created_at: new Date(Date.now() - 900000).toISOString(),
    updated_at: new Date(Date.now() - 896000).toISOString(),
  },
  {
    command_id: 'CMD-2026-0004',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_002',
    device_id: 'D004',
    command_type: 'set_position',
    command_payload: { target_position_pct: 50 },
    issued_by: 'USR_FARMER_001',
    issued_at: new Date(Date.now() - 300000).toISOString(),
    expires_at: new Date(Date.now() - 240000).toISOString(),
    current_ack_stage: 'rejected',
    result: 'failure',
    reason_code: 'RSN_MANUAL_ACTIVE',
    created_at: new Date(Date.now() - 300000).toISOString(),
    updated_at: new Date(Date.now() - 298000).toISOString(),
  },
];

// ─── EVENTS ──────────────────────────────────────────────────

export const MOCK_EVENTS: DeviceEvent[] = [
  {
    event_id: 'EVT-001',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_001',
    device_id: 'D001',
    event_code: 'EVT_VALVE_OPENED',
    severity: 'info',
    state_before: 'closed',
    state_after: 'open',
    is_active: false,
    ts_device: new Date(Date.now() - 3592000).toISOString(),
    ts_cloud: new Date(Date.now() - 3590000).toISOString(),
    seq: 1042,
  },
  {
    event_id: 'EVT-002',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_001',
    device_id: 'D003',
    event_code: 'EVT_FAULT_DETECTED',
    severity: 'error',
    state_before: 'opening',
    state_after: 'fault',
    fault_code: 'FLT_MOTOR_OVERCURRENT',
    is_active: true,
    ts_device: new Date(Date.now() - 895000).toISOString(),
    ts_cloud: new Date(Date.now() - 893000).toISOString(),
    seq: 445,
  },
  {
    event_id: 'EVT-003',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_001',
    device_id: 'D003',
    event_code: 'EVT_LOW_BATTERY',
    severity: 'warning',
    state_before: 'good',
    state_after: 'low',
    is_active: true,
    ts_device: new Date(Date.now() - 7200000).toISOString(),
    ts_cloud: new Date(Date.now() - 7198000).toISOString(),
    seq: 420,
  },
  {
    event_id: 'EVT-004',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_002',
    device_id: 'D004',
    event_code: 'EVT_MANUAL_ACTIVATED',
    severity: 'warning',
    state_before: 'closed',
    state_after: 'closed',
    reason_code: 'RSN_MANUAL_ACTIVE',
    is_active: true,
    ts_device: new Date(Date.now() - 1200000).toISOString(),
    ts_cloud: new Date(Date.now() - 1198000).toISOString(),
    seq: 321,
  },
  {
    event_id: 'EVT-005',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_002',
    device_id: 'D005',
    event_code: 'EVT_DEVICE_OFFLINE',
    severity: 'critical',
    state_before: 'online',
    state_after: 'offline',
    fault_code: 'FLT_LTE_DISCONNECTED',
    is_active: true,
    ts_device: new Date(Date.now() - 3620000).toISOString(),
    ts_cloud: new Date(Date.now() - 3618000).toISOString(),
    seq: 199,
  },
];

// ─── FAULTS ──────────────────────────────────────────────────

export const MOCK_FAULTS: Fault[] = [
  {
    fault_id: 'FLT-001',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_001',
    device_id: 'D003',
    fault_code: 'FLT_MOTOR_OVERCURRENT',
    severity: 'error',
    description: 'Motor overcurrent detected during valve opening cycle',
    is_active: true,
    detected_at: new Date(Date.now() - 895000).toISOString(),
    related_event_id: 'EVT-002',
  },
  {
    fault_id: 'FLT-002',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_001',
    device_id: 'D003',
    fault_code: 'FLT_BATTERY_LOW',
    severity: 'warning',
    description: 'Battery voltage below low threshold (10.5V)',
    is_active: true,
    detected_at: new Date(Date.now() - 7200000).toISOString(),
    related_event_id: 'EVT-003',
  },
  {
    fault_id: 'FLT-003',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_002',
    device_id: 'D005',
    fault_code: 'FLT_LTE_DISCONNECTED',
    severity: 'critical',
    description: 'LTE connection lost — device not reachable',
    is_active: true,
    detected_at: new Date(Date.now() - 3620000).toISOString(),
    related_event_id: 'EVT-005',
  },
  {
    fault_id: 'FLT-004',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_002',
    device_id: 'D005',
    fault_code: 'FLT_BATTERY_CRITICAL',
    severity: 'critical',
    description: 'Battery critically low — device may shut down',
    is_active: true,
    detected_at: new Date(Date.now() - 3600000).toISOString(),
  },
];

// ─── WEATHER CACHE ────────────────────────────────────────────

export const MOCK_WEATHER: WeatherCache[] = [
  {
    cache_id: 'WX-FARM-001',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_001',
    lat: 13.3409,
    lon: 74.7421,
    rain_probability_pct: 35,
    rain_forecast_mm: 8.2,
    temperature_min_c: 24,
    temperature_max_c: 32,
    humidity_pct: 78,
    wind_speed_kmh: 14,
    weather_description: 'Partly cloudy with chance of afternoon showers',
    irrigation_advisory: 'caution',
    advisory_reason: 'Moderate rain probability — consider reducing irrigation duration',
    fetched_at: new Date(Date.now() - 1800000).toISOString(),
    expires_at: new Date(Date.now() + 5400000).toISOString(),
  },
  {
    cache_id: 'WX-FARM-002',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_002',
    lat: 13.3398,
    lon: 74.7445,
    rain_probability_pct: 35,
    rain_forecast_mm: 8.2,
    temperature_min_c: 24,
    temperature_max_c: 32,
    humidity_pct: 78,
    wind_speed_kmh: 14,
    weather_description: 'Partly cloudy with chance of afternoon showers',
    irrigation_advisory: 'caution',
    advisory_reason: 'Moderate rain probability — consider reducing irrigation duration',
    fetched_at: new Date(Date.now() - 1800000).toISOString(),
    expires_at: new Date(Date.now() + 5400000).toISOString(),
  },
  {
    cache_id: 'WX-MUNI-001',
    tenant_id: 'TENANT_DEMO_MUNI',
    site_id: 'SITE_MUNI_001',
    lat: 13.3316,
    lon: 74.7459,
    rain_probability_pct: 15,
    rain_forecast_mm: 2.0,
    temperature_min_c: 25,
    temperature_max_c: 31,
    humidity_pct: 72,
    wind_speed_kmh: 12,
    weather_description: 'Mostly sunny',
    irrigation_advisory: 'proceed',
    fetched_at: new Date(Date.now() - 1800000).toISOString(),
    expires_at: new Date(Date.now() + 5400000).toISOString(),
  },
];

// ─── TELEMETRY HISTORY (for charts) ──────────────────────────

export function generateTelemetryHistory(device_id: string, tenant_id: string, site_id: string, count = 48): TelemetryHistory[] {
  const records: TelemetryHistory[] = [];
  const now = Date.now();
  const device = MOCK_LATEST_STATE.find(s => s.device_id === device_id);
  if (!device) return [];

  for (let i = count; i >= 0; i--) {
    const ts = new Date(now - i * 5 * 60 * 1000).toISOString();
    const noise = () => (Math.random() - 0.5) * 2;
    records.push({
      record_id: `TH-${device_id}-${i}`,
      device_id,
      tenant_id,
      site_id,
      valve_state: device.valve_state,
      valve_position_pct: Math.max(0, Math.min(100, device.valve_position_pct + noise() * 2)),
      battery_v: Math.max(9.0, Math.min(13.5, device.battery_v + noise() * 0.1)),
      signal_strength: Math.max(0, Math.min(100, device.signal_strength + noise() * 5)),
      motor_current_a: device.motor_current_a !== undefined ? Math.max(0, device.motor_current_a + noise() * 0.1) : undefined,
      ts_device: ts,
      seq: 1000 - i,
    });
  }
  return records;
}

// ─── SERVICE RECORDS ──────────────────────────────────────────

export const MOCK_SERVICE_RECORDS: ServiceRecord[] = [
  {
    service_ticket_id: 'SRV-2026-001',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_001',
    device_id: 'D003',
    service_status: 'open',
    service_priority: 'high',
    service_description: 'Motor overcurrent fault — check for physical obstruction and motor health',
    assigned_to_user_id: 'USR_SERVICE_001',
    fault_codes: ['FLT_MOTOR_OVERCURRENT'],
    created_at: new Date(Date.now() - 890000).toISOString(),
    updated_at: new Date(Date.now() - 890000).toISOString(),
  },
  {
    service_ticket_id: 'SRV-2026-002',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_002',
    device_id: 'D005',
    service_status: 'open',
    service_priority: 'critical',
    service_description: 'Device offline — LTE connection lost. Critical battery. Physical site visit required.',
    assigned_to_user_id: 'USR_SERVICE_001',
    fault_codes: ['FLT_LTE_DISCONNECTED', 'FLT_BATTERY_CRITICAL'],
    created_at: new Date(Date.now() - 3610000).toISOString(),
    updated_at: new Date(Date.now() - 3610000).toISOString(),
  },
];

// ─── SCHEDULES ───────────────────────────────────────────────

const _now = Date.now();

export const MOCK_SCHEDULES: Schedule[] = [
  {
    schedule_id: 'SCH-001',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_001',
    device_id: 'D001',
    schedule_name: 'Morning Irrigation — Borewell 1',
    schedule_type: 'daily',
    command_type: 'open',
    planned_start_at: new Date(_now + 6 * 3600000).toISOString(),
    planned_duration_min: 45,
    target_device_ids: ['D001', 'D002'],
    schedule_status: 'planned',
    water_confirmation_required: false,
    enabled: true,
    recurrence_rule: 'FREQ=DAILY;BYHOUR=6;BYMINUTE=0',
    created_by: 'USR_FARMER_001',
    created_at: new Date(_now - 7 * 86400000).toISOString(),
    updated_at: new Date(_now - 86400000).toISOString(),
  },
  {
    schedule_id: 'SCH-002',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_001',
    device_id: 'D001',
    schedule_name: 'Evening Close — Borewell 1',
    schedule_type: 'daily',
    command_type: 'close',
    planned_start_at: new Date(_now + 12 * 3600000).toISOString(),
    planned_duration_min: undefined,
    target_device_ids: ['D001', 'D002'],
    schedule_status: 'planned',
    water_confirmation_required: false,
    enabled: true,
    recurrence_rule: 'FREQ=DAILY;BYHOUR=18;BYMINUTE=30',
    created_by: 'USR_FARMER_001',
    created_at: new Date(_now - 7 * 86400000).toISOString(),
    updated_at: new Date(_now - 86400000).toISOString(),
  },
  {
    schedule_id: 'SCH-003',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_002',
    device_id: 'D004',
    schedule_name: 'Drip Irrigation — South Field (50%)',
    schedule_type: 'weekly',
    command_type: 'set_position',
    target_position_pct: 50,
    planned_start_at: new Date(_now + 2 * 86400000).toISOString(),
    planned_duration_min: 90,
    target_device_ids: ['D004', 'D005'],
    schedule_status: 'planned',
    water_confirmation_required: true,
    enabled: true,
    recurrence_rule: 'FREQ=WEEKLY;BYDAY=MO,WE,FR',
    created_by: 'USR_FARMER_001',
    created_at: new Date(_now - 3 * 86400000).toISOString(),
    updated_at: new Date(_now - 3 * 86400000).toISOString(),
  },
  {
    schedule_id: 'SCH-004',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_001',
    device_id: 'D002',
    schedule_name: 'One-time Emergency Open — Drip Line 2',
    schedule_type: 'one_time',
    command_type: 'open',
    planned_start_at: new Date(_now - 3600000).toISOString(),
    planned_duration_min: 30,
    target_device_ids: ['D002'],
    schedule_status: 'confirmed',
    water_confirmation_required: false,
    enabled: false,
    created_by: 'USR_FARMER_001',
    created_at: new Date(_now - 4 * 3600000).toISOString(),
    updated_at: new Date(_now - 3500000).toISOString(),
  },
  {
    schedule_id: 'SCH-005',
    tenant_id: 'TENANT_DEMO_AGRI',
    site_id: 'SITE_FARM_002',
    device_id: 'D005',
    schedule_name: 'Weekly Calibration — Field South Valve',
    schedule_type: 'weekly',
    command_type: 'calibrate',
    planned_start_at: new Date(_now - 86400000).toISOString(),
    target_device_ids: ['D005'],
    schedule_status: 'failed',
    water_confirmation_required: false,
    enabled: false,
    recurrence_rule: 'FREQ=WEEKLY;BYDAY=SU',
    created_by: 'USR_ADMIN_001',
    created_at: new Date(_now - 14 * 86400000).toISOString(),
    updated_at: new Date(_now - 86000000).toISOString(),
  },
];
